name: 'terraform fmt, init, validate and plan on PR'
on: pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # TERRAFORM_VERSION: ${{ secrets.TERRAFORM_VERSION }} 
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plna
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
