name: 'terraform fmt, init, validate and plan on PR'
on: pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # TERRAFORM_VERSION: ${{ secrets.TERRAFORM_VERSION }} 
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Terraform Format'
        uses: hashicorp/setup-terraform@v1
        with:
          # tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'fmt'

      - name: 'Terraform Init'
        uses: hashicorp/setup-terraform@v1
        with:
          # tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'init'

      - name: 'Terraform Validate'
        uses: hashicorp/setup-terraform@v1
        with:
          # tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'validate'

      - name: 'Terraform Plan'
        uses: hashicorp/setup-terraform@v1
        with:
          # tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'plan'
